### ISSUE TITLE
baseUrl is not absolute

### ISSUE THREAD

**Issue by ismell** [hearsayit/HearsayRequireJSBundle#1]
My template has the following

```
{% block javascripts %}
    {{ parent() }}
    <script type='text/javascript'>require(['wedcore/edit'], function() {})</script>
{% endblock %}
```

My Config looks like so

```

hearsay_require_js:
    base_directory: %kernel.root_dir%/scripts
    paths: 
        jquery:
            location: //ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min
            external: true
        wedcore: '@WedCoreBundle/Resources/scripts'
    optimizer:
        path: /path/to/r.js
        excludes: [ excluded/module ] # Modules to exclude from the build (optional)
        options: { skipModuleInsertion: true } # Additional options to pass to the optimizer (optional)
```

When I hit the following url: http://rangelwed/app_dev.php/reception/edit

My require block generates the following

```
<script type='text/javascript'>var require={"baseUrl":"js","locale":null,"paths":{"jquery":"\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/1.7.1\/jquery.min"}}</script><script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/require.js/1.0.1/require.min.js'></script>

<script type='text/javascript'>require(['wedcore/edit'], function() {})</script>
```

if you notice the baseUrl it's relative. This causes the request to wedcore/edit to go to http://rangelwed/app_dev.php/reception/js/wedcore/edit.js. This is incorrect and instead should go to http://rangelwed/app_dev.php/js/wedcore/edit.js.

So the base URL should be rendered as /app_dev.php/js/.

Thanks,
Raul

**Comment by bigethan** [comment]
in your config.yml you can specify 

``` yaml
hearsay_require_js:
    ...
    base_url: /js 
```

in your main config, and then in your config_dev.yml do:

``` yaml
hearsay_require_js:
    base_url: /app_dev.php/js
```

and that should get you want you want.
