### ISSUE TITLE
Assets config not being included

### ISSUE THREAD

**Issue by hardchor** [hearsayit/HearsayRequireJSBundle#18]
Hi there.

Following config:

``` yaml
hearsay_require_js:
    base_directory: "%kernel.root_dir%/../src/Acme/DemoBundle/Resources/public/js"
    base_url:       "/bundles/acmedemobundle/js"
    require_js_src: "/bundles/acmedemobundle/js/vendors/require.js"
    paths:
        # these dont work
        frontend:       "%kernel.root_dir%/../src/Acme/DemoBundle/Resources/public/js"
```

I'm also serving assets statically (i.e. not through the assetic controller) and am don't have r.js configured (I assume this is optional).

The `paths` directive is not being passed through to the view. 
Looking through [HearsayRequireJSExtension.php](https://github.com/hearsayit/HearsayRequireJSBundle/blob/master/DependencyInjection/HearsayRequireJSExtension.php)'s method `addExternalNamespaceMapping` line #136 adds paths for external pages:

``` php
$config->addMethodCall('setPath', array($path, $location));
```

However, the equivalent method for internal pages `addNamespaceMapping` doesn't contain any such call. 

Is there any reason for this? Maybe I'm missing something?

**Comment by ihortymoshenko** [comment]
I think this is not necessary. Is it creates any problems?

**Comment by sprain** [comment]
Could it be I am struggling with the same issue?
http://stackoverflow.com/questions/15680066/hearsayrequirejsbundle-javascript-files-not-found

**Comment by ihortymoshenko** [comment]
@sprain, are you sure that the path is exists? The `addExternalNamespaceMapping` method will be executed only if the path is an external. Perhaps, you specified the wrong path. Symfony contains resources such as css, images and js under the `Resources` directory in the directories with related names. Check again please.

**Comment by sprain** [comment]
@IgorTimoshenko I might be misunderstanding something. So it isn't possible to keep JS files outside of the public folder and only serve them with Assetic over dynamically generated routes?

**Comment by ihortymoshenko** [comment]
@sprain, I meant that you should check whether the specified path is real.

**Comment by craigmarvelley** [comment]
Also ensure that you clear your Symfony cache after registering new paths, that's caught me out a few times.

**Comment by jeremymarc** [comment]
I'm getting the same problem. 

When I'm not using "external: true", paths for internal location are not output with the require config file (so requirejs cannot find my modules).
We need it for modules which are not located in the base_directory.

I've found a workaround, using "external: true" and specifying the location like this: "/bundles/acme/js" cc @hardchor.

**Comment by craigmarvelley** [comment]
@hardchor The paths configuration node is for defining additional paths to the `base_directory`, which is the default. So the `frontend` path is redundant - your scripts should be available from the base directory.

Assuming you have this dir structure:

```
<bundle dir>
|_  Resources
     |_   scripts
          |_   main.js
```

and you're trying to load the main script like this:

```
{{ require_js_initialize({ 'main' : 'frontend/main' }) }}
```

Try removing that frontend path from the config, and instead load your main script like this:

```
{{ require_js_initialize({ 'main' : 'main' }) }}
```

AFAIK the `base_url` configuration is not necessary.

**Comment by hardchor** [comment]
Hi,

Having finally got the time to get back to this, I've got a bit of a better understanding of require and the bundle.

Many libraries like jquery plugins, moment.js etc. require named modules (i.e. jQuery defined as `"jquery"` and moment.js as `"moment"`). In vanilla require.js I'd define path aliases like so:

``` javascript
{
    baseUrl: "/bundles/acmedemo/js",
    paths: {
        controller: "src/controller",
        jquery: "vendor/jquery"
    }
}
```

The paths config for the bundle is not the same as for requirejs in that it tries to prefix any path key with the base URL (that's in [NamespaceMapping.php#L83](https://github.com/hearsayit/HearsayRequireJSBundle/blob/master/Configuration/NamespaceMapping.php#L83)). 
So, with the above config the bundle spits out paths like `/bundles/acmedemo/js/jquery` (which doesn't exist).

Am I doing something fundamentally wrong (it's working in require.js, so perhaps I'm not) or is there a reason why `NamespaceMapping` prepends the base URL to path configs rather than just passing them through to require.js?

**Comment by ihortymoshenko** [comment]
@hardchor, yes, you're right. The `paths` configuration is not the same.

You can specify in the `paths` configuration option:
- a namespace as a prefix to prefix some module directory;
- a concrete file without the `.js` file extension.

The main goal of this bundle is to expose directories where you store JavaScript files in order to provide the ability to the `RequireJS` load this files as modules.

That's current implementation. If you have proposals, feel free to contribute.

**Comment by hardchor** [comment]
I'm struggling to see a scenario where this would actually work as intended. Let's say I've got a `AcmeDemoBundle` and an `AcmeOtherBundle`. Now assuming the following `config.yml`:

``` yml
hearsay_require_js:
    base_directory: "@AcmeDemoBundle/Resources/public/js"
    base_url:       "/bundles/acmedemo/js"
    require_js_src: "/bundles/acmedemo/js/vendor/require.js"
    paths:
        # make jQuery available as "jquery"
        jquery:     "@AcmeDemoBundle/Reosurces/public/js/vendor/jquery-2.0.1"
        # make "OtherBundle" resources available via "other" prefix
        other:       "@AcmeOtherBundle/Resources/public/js"
```

This would output the following require.js config:

``` javascript
var require = {
    baseUrl: "/bundles/acmedemo/js",
    paths: {
        "jquery" "/bundles/acmedemo/js/jquery" // <- this is where it goes wrong
        "other": "/bundles/acmedemo/js/other"  // not what I had in mind either
}
```

I think what I'll have to do to get around the named modules problem at least is to set my `base_url` as `/bundles/acmedemo/js/vendor`, rename `jquery-2.0.1.js` to `jquery.js` and then perhaps specify any other paths as externals.
