### ISSUE TITLE
RequireJSBundle should use assets_base_urls

### ISSUE THREAD

**Issue by kayue** [hearsayit/HearsayRequireJSBundle#19]
I use the following config in my config.yml to enable CDN:

```
framework:
    templating:
        engines: ['twig']
        assets_base_urls:
            http: ['http://cdn.example.com']
```

I think RequireJSBundle should use `assets_base_urls` the settings too.

Is there any other way we can enable CDN?
