### ISSUE TITLE
RequireJSOptimizerFilter and r.js version 2.1.5

### ISSUE THREAD

**Issue by jeelo** [hearsayit/HearsayRequireJSBundle#28]
Hi,

I'm fighting a little to get this bundle working when using "php app/console assetic:dump --env=prod --no-debug" and the latest version of r.js ( 2.1.5 )

When specifying the following config in config.yml everything works fine on app_dev.php/:

hearsay_require_js:
    optimizer:
        path: /opt/local/lib/node_modules/requirejs/bin/r.js
        options: { skipModuleInsertion: true }
    base_directory: %kernel.root_dir%/Resources/js
    paths:
        jquery: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js

But when dumping the assets i get the following error:
Error: ENOENT, no such file or directory '/Users/jeroen/Projects/sandwidgetspread/app/../vendor/jquery/jquery/jquery-1.9.1.js.js'

Please note the double .js.js extension!

r.js seems to want the path without the extension.

Am I doing something wrong or is this bundle not compatible with this version of r.js ?

Many thanks!

**Comment by hardchor** [comment]
Have you tried specifying the jquery path without the .j's suffix?

**Comment by jameshalsall** [comment]
@IgorTimoshenko @kmontag  I think this is an issue, I get the same error when using requirejs 2.1.8 and the new shim:

My config for requirejs:

``` yaml
hearsay_require_js:
    require_js_src: http://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.8/require.min.js
    optimizer:
        path: %requirejs_bin%
    base_directory: %kernel.root_dir%/Resources/public/js
    paths:
        jquery: "@AcmeCoreBundle/Resources/public/js/vendor/jquery/jquery"
        jqueryui: %kernel.root_dir%/Resources/public/js/vendor/jquery-ui-1.10.3.min
    shim:
        -
            name: jquery
            exports: '$'
        -
            name: jqueryui
            deps: [jquery]
```

I initialise with the usual block and filter:

``` twig
{% javascripts filter='requirejs' '@AcmeCoreBundle/Resources/public/js/App.js' %}
    {{ require_js_initialize({ 'main' : asset_url }) }}
{% endjavascripts %}
```

My `App.js` looks like:

``` javascript
    require([
    'jquery',
    'jqueryui'
], function() {
    // do some stuff
});
```

The output of my App.js file shows an error:

> exception] 500 | Internal Server Error | RuntimeException
> [message] Optimization failed: 
> Tracing dependencies for: 3c232fb4317c3fdfa4dad91432e6d7a6
> Error: ENOENT, no such file or directory > &#039;/Library/WebServer/Documents/tickit/src/Tickit/CoreBundle/Resources/public/js/vendor/jquery/jquery.js.js&#039;
> In module tree:
>    3c232fb4317c3fdfa4dad91432e6d7a6

For some reason it's double suffixing the jquery library, but as you can see I'm not defining it with with the suffix in my paths config.
