### ISSUE TITLE
Define path fallback in the configuration file?

### ISSUE THREAD

**Issue by rayrigam** [hearsayit/HearsayRequireJSBundle#29]
I'm using the latest version of this bundle with Symfony 2.2 and would like to use external scripts loaded from a CDN for the require.min.js, jquery and other files. I tried the following in my Symfony2 config.yml file:

``` yaml
hearsay_require_js:
    base_directory: %kernel.root_dir%/../src/MyVendor/MyBundle/Resources/public/js
    require_js_src: [//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.5/require.min.js, /js/libs/require/2.1.5/require.min.js]
    paths:
        jquery:
            location: [//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min, /js/libs/jquery/2.0.0/jquery.min]
            external: true
```

However, the following error was thrown when updating the autoload file with composer update: `Invalid type for path "hearsay_require_js.require_js_src". Expected scalar, but got array.` Is there a way to define local fallbacks when external CDN resources are used? Would the "external: true" definition still apply if the fallback is used?

**Comment by ihortymoshenko** [comment]
@rayrigam, try to define a few paths with different names.

**Comment by rayrigam** [comment]
@IgorTimoshenko , if I do that it seems like I would have to write a condition in my main or modules files to check if the scripts from the CDN loaded (and if not load the local ones), which is what I was trying to avoid. It seems like I could do it from within the requirejs.config definition in my main.js file as shown here http://stackoverflow.com/a/12075285, moving all the paths definition to main.js, but I would still not be able to define a fallback for the require.min.js file...

**Comment by ihortymoshenko** [comment]
@rayrigam, looks like it is possible to add the ability to specify array values for the `paths` config. I will add this ASAP.

**Comment by rayrigam** [comment]
@IgorTimoshenko , good to hear! Looking forward to it!

**Comment by rayrigam** [comment]
@IgorTimoshenko Thanks! The paths now work with arrays to be able to define fallback files (which is what I was looking for). However, it is worth mentioning that paths locations do not work with strings anymore in the new bundle version. People will need to update by adding square brackets to the paths defined in the config.yml file. Also, one more question: is there a way to define a fallback for the  require.min.js file itself? defined in:

``` yaml
hearsay_require_js:
    base_directory: %kernel.root_dir%/../src/Groupidea/SiteBundle/Resources/public/js
    require_js_src: //cdnjs.cloudflare.com/ajax/libs/require.js/2.1.5/require.min.js
```

It would be nice to be able to define an array for the `require_js_src` as well (as above). It still only accepts a scalar/string...
