### ISSUE TITLE
Assetic filter with production flag causes 404 errors in dev environment

### ISSUE THREAD

**Issue by benglass** [hearsayit/HearsayRequireJSBundle#44]
Using the 1.0 branch (because it supports build_profie, see #43) with use_controller: true for assetic in dev environment to dynamically generate assets on page load and using the assetic filter with the production flag (see example below) I end up with 404s in dev environment. It seems the asset url should still be generated but the filter should just not be applied. Instead it seems that the asset is not generated at all but the url is returned as /js/foo.js which is not served by assetic and is a 404.

``` yml
{% javascripts
    filter='?requirejs'
    '@AcmeDemoBundle/Resources/public/js/src/main.js'
%}
```

**Comment by ihortymoshenko** [comment]
@afishnamedsquish, looks like you're right. I've just tried to run the test application on the `1.0` branch and I caught the same issue. I'll see what we can do and give you a feedback.

**Comment by benglass** [comment]
@IgorTimoshenko I actually figured out what was causing this which is that when you use the @Bundle notation in your paths config you end up with an absolute path to the module that does NOT include the dev environment prefix of app_dev.php. This means that assetic's asset controller is not triggered even if you have use_controller set to true. It seems to be fixed in the 2.0 branch.

**Comment by ihortymoshenko** [comment]
@afishnamedsquish, in the `2.0` branch the `baseUrl` configuration option contains the script. I think I can port this file into the `1.0` branch but a little bit later when I'll fix a small undocumented issue.

**Comment by ronnbot** [comment]
Just switched to 2.0 and when trying to optimize in my local dev, optimization doesn't seem to be working, i.e. 404 error: 

{% javascripts filter='requirejs' '@AcmeDemoBundle/Resources/public/js/src/main.js' %}
    {{ require_js_initialize({ 'main' : asset_url }) }}
{% endjavascripts %}

I can still manually optimize via the command line no problem:

node lib/r.js -o app.build.js

Is this related? I just started using the bundle. Thanks.

**Comment by ihortymoshenko** [comment]
@ronnbot, can you provide your bundle configuration? What is this file `app.build.js`? The bundle doesn't provide such file.

**Comment by ronnbot** [comment]
app.build.js:

```
(function() {
    return {
        appDir: ".",
        baseUrl: ".",
        dir: "../build",
        preserveLicenseComments: true,
        keepBuildDir: true,
        findNestedDependencies: true,
        paths: {
            "jquery": "lib/jquery",
            "backbone": "lib/backbone",
            "text": "lib/require-text",
            "handlebars": "lib/handlebars",
            "underscore": "lib/underscore",
            "backbone-relational": "lib/backbone-relational"
        },
        shim: {
            'lib/jquery': {
                exports: '$'
            },
            'lib/handlebars': {
                exports: 'Handlebars'
            },
            'lib/underscore': {
                exports: '_'
            },
            'lib/backbone': {
                deps: ['lib/underscore', 'lib/jquery'],
                exports: 'Backbone'
            },
            'lib/backbone-relational': {
                deps: ['lib/backbone']
            }
        },

        modules: [{
            name: "main/index"
        }]
    }
})()
```

Just for reference, here's the settings from config.yml:

```
# Require js
hearsay_require_js:
    require_js_src: //cdnjs.cloudflare.com/ajax/libs/require.js/2.1.8/require.min.js
    base_url: js
    base_dir: '@AcmeDemoBundle/Resources/public/js'
    paths: 
        text: '@AcmeDemoBundle/Resources/public/js/lib/require-text'
    shim:
        -
            name: lib/jquery
            exports: '$'
        -
            name: lib/handlebars
            exports: 'Handlebars'
        -
            name: lib/underscore
            exports: '_'
        -
            name: lib/backbone
            deps: [ lib/underscore, lib/jquery ]
            exports: 'Backbone'
        -
            name: lib/backbone-relational
            deps: [ lib/backbone ]
    optimizer:
        path: '@AcmeDemoBundle/Resources/public/js/lib/r.js'
```
