### ISSUE TITLE
directories specified in the array "paths" in yml configuration file are not processed correctly

### ISSUE THREAD

**Issue by apsavin** [hearsayit/HearsayRequireJSBundle#59]
part of my yml configuration file:

``` yml
hearsay_require_js:
  initialize_template: HearsayRequireJSBundle::initialize.html.twig
  base_dir: "%kernel.root_dir%/Resources/public/js"
  base_url: "compiled/js/require"
  paths:
    global: "%kernel.root_dir%/Resources/global/js"
```

Actual result in generated config:

``` javascript
var require={"baseUrl":"/compiled/js/require","locale":"en","paths":{"global":"/compiled/js/require/global/js"
```

Expected result in generated config:

``` javascript
var require={"baseUrl":"/compiled/js/require","locale":"en","paths":{"global":"/compiled/js/require/global"
```

As you can see, js subdirectory is redundant here: 
/compiled/js/require/global__/js__
